using UnityEngine;
using System.Collections;

public class SingletonMono<T> : MonoBehaviour where T : MonoBehaviour
{
    private static T instance;

    public static T Instance
    {
        get
        {
            if (instance == null)
            {
                instance = FindObjectOfType(typeof(T)) as T;

                if (instance == null)
                {
                    GameObject host = new GameObject();
                    instance = host.AddComponent<T>();
                    host.name = "_" + instance.GetType().ToString() + "[autogenerated]";
                }
            }

            return (T)instance;
        }
    }

    protected virtual bool IsGlobalScope
    {
        get
        {
            return false;
        }
    }

    protected virtual void Awake()
    {
        this.OnAwake();
    }

    protected virtual void OnAwake()
    {
        if (this.IsGlobalScope)
        {
            UnityEngine.Object.DontDestroyOnLoad(this.gameObject);
        }
    }
}
